<?xml version="1.0"?>
<!-- Arm description for Turtlebot Arm and PhantomX Pincher arm -->
<robot xmlns:xacro="http://ros.org/wiki/xacro">

  <material name="White">
    <color rgba="0.87 0.90 0.87 1.0"/>
  </material>
  <material name="Black">
    <color rgba="0.08 0.08 0.08 1.0"/>
  </material>
  <material name="Gray">
    <color rgba="0.2 0.2 0.21 1.0"/>
  </material>
  <material name="Green">
    <color rgba="0.22 0.32 0.14 1.0"/>
  </material>

 <link name="arm_base_link" />
    <joint name="arm_base_joint" type="fixed">
        <origin xyz="${origin_arm}" />
        <parent link="base_link" />
        <child link="arm_base_link" />
    </joint>

    <joint name="arm_shoulder_pan_servo_joint" type="fixed">
        <origin rpy="1.570795 0 1.570795" xyz="0 0 0" />
        <parent link="arm_base_link" />
        <child link="arm_shoulder_pan_servo_link" />
    </joint>

    <link name="arm_shoulder_pan_servo_link">
	<inertial>
            <mass value="0.055" />
            <origin xyz="0 0 0" />
            <inertia ixx="0.000017012" ixy="0.0" ixz="0.0" iyy="0.000013258" iyz="0.0" izz="0.000009483" />
	    <dynamics damping="0.5" friction="0.1"/>
        </inertial>

        <visual>
            <origin rpy="0 0 0" xyz=" 0 0 0 " />
            <geometry>
                <mesh filename="file://$(find cookobot-arm)/robot_description/urdf/meshes/arm/ax12_box.stl" scale="0.001 0.001 0.001" />
            </geometry>
            <material name="Black" />
        </visual>
        <collision>
            <origin rpy="0 0 0" xyz="0.0 0.0 -0.01241" />
            <geometry>
                <box size="0.025 0.038 0.04762" />
            </geometry>
        </collision>
    </link>

    <joint name="arm_shoulder_pan_joint" type="revolute">
        <origin rpy="-1.570795 1.570795 3.14159" xyz="0 0.019 0" />
        <axis xyz="0 0 -1" />
        <limit effort="30" lower="-2.617" upper="2.617" velocity="1.571" />
        <parent link="arm_shoulder_pan_servo_link" />
        <child link="arm_shoulder_pan_link" />
    </joint>
     
    <link name="arm_shoulder_pan_link">
        <inertial>
            <mass value="0.008" />
            <origin xyz="0 0 0" />
            <inertia ixx="4.70666666667e-07" ixy="0" ixz="0" iyy="1.37933333333e-06" iyz="0" izz="1.01666666667e-06" />
	    <dynamics damping="0.5" friction="0.1"/>
        </inertial>

        <visual>
            <origin rpy="0 0 0" xyz=" 0 0 0 " />
            <geometry>
                <mesh filename="file://$(find cookobot-arm)/robot_description/urdf/meshes/arm/F3.stl" scale="0.001 0.001 0.001" />
            </geometry>
            <material name="White" />
        </visual>
        <collision>
            <origin rpy="0 0 0" xyz="0.0 0.0 -0.0045" />
            <geometry>
                <box size="0.025 0.038 0.009" />
            </geometry>
        </collision>
    </link>

    <joint name="arm_shoulder_lift_servo_joint" type="fixed">
        <origin rpy="0 3.14159 0" xyz="0 0 -0.0415" />
        <parent link="arm_shoulder_pan_link" />
        <child link="arm_shoulder_lift_servo_link" />
    </joint>
    <link name="arm_shoulder_lift_servo_link">

    <inertial>
            <mass value="0.055" />
            <origin xyz="0 0 0" />
            <inertia ixx="0.000017012" ixy="0.0" ixz="0.0" iyy="0.000013258" iyz="0.0" izz="0.000009483" />
	    <dynamics damping="0.5" friction="0.1"/>
    </inertial>

        <visual>
            <origin rpy="0 0 0" xyz=" 0 0 0 " />
            <geometry>
                <mesh filename="file://$(find cookobot-arm)/robot_description/urdf/meshes/arm/ax12_box.stl" scale="0.001 0.001 0.001" />
            </geometry>
            <material name="Black" />
        </visual>
        <collision>
            <origin rpy="0 0 0" xyz="0.0 0.0 -0.01241" />
            <geometry>
                <box size="0.025 0.038 0.04762" />
            </geometry>
        </collision>
    </link>

    <joint name="arm_shoulder_lift_joint" type="revolute">
        <origin rpy="0 0 0" xyz="0 0 0" />
        <axis xyz="0 1 0" />
        <limit effort="30" lower="-2.617" upper="2.617" velocity="1.571" />
        <parent link="arm_shoulder_lift_servo_link" />
        <child link="arm_shoulder_lift_link" />
    </joint>
    <link name="arm_shoulder_lift_link">

    <inertial>
            <mass value="0.016" />
            <origin xyz="0 0 0" />
            <inertia ixx="6.67866666667e-06" ixy="0" ixz="0" iyy="4.18166666667e-06" iyz="0" izz="8.76966666667e-06" />
	    <dynamics damping="0.5" friction="0.1"/>
        </inertial>

        <visual>
            <origin rpy="0 0 0" xyz=" 0 0 0 " />
            <geometry>
                <mesh filename="file://$(find cookobot-arm)/robot_description/urdf/meshes/arm/F4.stl" scale="0.001 0.001 0.001" />
            </geometry>
            <material name="White" />
        </visual>
        <collision>
            <origin rpy="0 0 0" xyz="0.0 0.0 0.0215" />
            <geometry>
                <box size="0.028 0.0485 0.065" />
            </geometry>
        </collision>
    </link>

    <joint name="arm_shoulder_F10_0_joint" type="fixed">
        <origin rpy="0 0 0" xyz="0 0 0.0545" />
        <parent link="arm_shoulder_lift_link" />
        <child link="arm_shoulder_F10_0_link" />
    </joint>
    <link name="arm_shoulder_F10_0_link">

    <inertial>
            <mass value="0.004" />
            <origin xyz="0 0 0" />
            <inertia ixx="2.13666666667e-07" ixy="0" ixz="0" iyy="6.89666666667e-07" iyz="0" izz="4.86666666667e-07" />
	    <dynamics damping="0.5" friction="0.1"/>
        </inertial>

        <visual>
            <origin rpy="0 0 0" xyz=" 0 0 0 " />
            <geometry>
                <mesh filename="file://$(find cookobot-arm)/robot_description/urdf/meshes/arm/F10.stl" scale="0.001 0.001 0.001" />
            </geometry>
            <material name="White" />
        </visual>
        <collision>
            <origin rpy="0 0 0" xyz="0.0 0.0 0.0" />
            <geometry>
                <box size="0.025 0.038 0.004" />
            </geometry>
        </collision>
    </link>

    <joint name="arm_shoulder_F10_1_joint" type="fixed">
        <origin rpy="0 0 0" xyz="0 0 0.004" />
        <parent link="arm_shoulder_F10_0_link" />
        <child link="arm_shoulder_F10_1_link" />
    </joint>
    <link name="arm_shoulder_F10_1_link">

    <inertial>
            <mass value="0.004" />
            <origin xyz="0 0 0" />
            <inertia ixx="2.13666666667e-07" ixy="0" ixz="0" iyy="6.89666666667e-07" iyz="0" izz="4.86666666667e-07" />
	    <dynamics damping="0.5" friction="0.1"/>
        </inertial>

        <visual>
            <origin rpy="0 0 0" xyz=" 0 0 0 " />
            <geometry>
                <mesh filename="file://$(find cookobot-arm)/robot_description/urdf/meshes/arm/F10.stl" scale="0.001 0.001 0.001" />
            </geometry>
            <material name="White" />
        </visual>
        <collision>
            <origin rpy="0 0 0" xyz="0.0 0.0 0.0" />
            <geometry>
                <box size="0.025 0.038 0.004" />
            </geometry>
        </collision>
    </link>

    <joint name="arm_shoulder_F10_2_joint" type="fixed">
        <origin rpy="0 0 0" xyz="0 0 0.004" />
        <parent link="arm_shoulder_F10_1_link" />
        <child link="arm_shoulder_F10_2_link" />
    </joint>
    <link name="arm_shoulder_F10_2_link">

    <inertial>
            <mass value="0.004" />
            <origin xyz="0 0 0" />
            <inertia ixx="2.13666666667e-07" ixy="0" ixz="0" iyy="6.89666666667e-07" iyz="0" izz="4.86666666667e-07" />
	    <dynamics damping="0.5" friction="0.1"/>
        </inertial>

        <visual>
            <origin rpy="0 0 0" xyz=" 0 0 0 " />
            <geometry>
                <mesh filename="file://$(find cookobot-arm)/robot_description/urdf/meshes/arm/F10.stl" scale="0.001 0.001 0.001" />
            </geometry>
            <material name="White" />
        </visual>
        <collision>
            <origin rpy="0 0 0" xyz="0.0 0.0 0.0" />
            <geometry>
                <box size="0.025 0.038 0.004" />
            </geometry>
        </collision>
    </link>

    <joint name="arm_shoulder_F3_0_joint" type="fixed">
        <origin rpy="0 3.14159 0" xyz="0 0 0.002" />
        <parent link="arm_shoulder_F10_2_link" />
        <child link="arm_shoulder_F3_0_link" />
    </joint>
    <link name="arm_shoulder_F3_0_link">

   <inertial>
            <mass value="0.005" />
            <origin xyz="0 0 0" />
            <inertia ixx="2.94166666667e-07" ixy="0" ixz="0" iyy="8.62083333333e-07" iyz="0" izz="6.35416666667e-07" />
	    <dynamics damping="0.5" friction="0.1"/>
        </inertial>

        <visual>
            <origin rpy="0 0 0" xyz=" 0 0 0 " />
            <geometry>
                <mesh filename="file://$(find cookobot-arm)/robot_description/urdf/meshes/arm/F3.stl" scale="0.001 0.001 0.001" />
            </geometry>
            <material name="White" />
        </visual>
        <collision>
            <origin rpy="0 0 0" xyz="0.0 0.0 -0.0045" />
            <geometry>
                <box size="0.025 0.038 0.009" />
            </geometry>
        </collision>
    </link>

    <joint name="arm_elbow_flex_servo_joint" type="fixed">
        <origin rpy="0 3.14159 0" xyz="0 0 -0.0415" />
        <parent link="arm_shoulder_F3_0_link" />
        <child link="arm_elbow_flex_servo_link" />
    </joint>
    <link name="arm_elbow_flex_servo_link">

   <inertial>
            <mass value="0.055" />
            <origin xyz="0 0 0" />
            <inertia ixx="0.000017012" ixy="0.0" ixz="0.0" iyy="0.000013258" iyz="0.0" izz="0.000009483" />
	    <dynamics damping="0.5" friction="0.1"/>
        </inertial>

        <visual>
            <origin rpy="0 0 0" xyz=" 0 0 0 " />
            <geometry>
                <mesh filename="file://$(find cookobot-arm)/robot_description/urdf/meshes/arm/ax12_box.stl" scale="0.001 0.001 0.001" />
            </geometry>
            <material name="Black" />
        </visual>
        <collision>
            <origin rpy="0 0 0" xyz="0.0 0.0 -0.01241" />
            <geometry>
                <box size="0.025 0.038 0.04762" />
            </geometry>
        </collision>
    </link>

    <joint name="arm_elbow_flex_joint" type="revolute">
        <origin rpy="0 0 0" xyz="0 0 0" />
        <axis xyz="0 1 0" />
        <limit effort="30" lower="-2.617" upper="2.617" velocity="1.571" />
        <parent link="arm_elbow_flex_servo_link" />
        <child link="arm_elbow_flex_link" />
    </joint>
    <link name="arm_elbow_flex_link">

   <inertial>
            <mass value="0.016" />
            <origin xyz="0 0 0" />
            <inertia ixx="6.67866666667e-06" ixy="0" ixz="0" iyy="4.18166666667e-06" iyz="0" izz="8.76966666667e-06" />
	    <dynamics damping="0.5" friction="0.1"/>
        </inertial>

        <visual>
            <origin rpy="0 0 0" xyz=" 0 0 0 " />
            <geometry>
                <mesh filename="file://$(find cookobot-arm)/robot_description/urdf/meshes/arm/F4.stl" scale="0.001 0.001 0.001" />
            </geometry>
            <material name="White" />
        </visual>
        <collision>
            <origin rpy="0 0 0" xyz="0.0 0.0 0.0215" />
            <geometry>
                <box size="0.028 0.0485 0.065" />
            </geometry>
        </collision>
    </link>

    <joint name="arm_elbow_F10_0_joint" type="fixed">
        <origin rpy="0 0 0" xyz="0 0 0.0545" />
        <parent link="arm_elbow_flex_link" />
        <child link="arm_elbow_F10_0_link" />
    </joint>
    <link name="arm_elbow_F10_0_link">

    <inertial>
            <mass value="0.004" />
            <origin xyz="0 0 0" />
            <inertia ixx="2.13666666667e-07" ixy="0" ixz="0" iyy="6.89666666667e-07" iyz="0" izz="4.86666666667e-07" />
	    <dynamics damping="0.5" friction="0.1"/>
        </inertial>

        <visual>
            <origin rpy="0 0 0" xyz=" 0 0 0 " />
            <geometry>
                <mesh filename="file://$(find cookobot-arm)/robot_description/urdf/meshes/arm/F10.stl" scale="0.001 0.001 0.001" />
            </geometry>
            <material name="White" />
        </visual>
        <collision>
            <origin rpy="0 0 0" xyz="0.0 0.0 0.0" />
            <geometry>
                <box size="0.025 0.038 0.004" />
            </geometry>
        </collision>
    </link>

    <joint name="arm_elbow_F10_1_joint" type="fixed">
        <origin rpy="0 0 0" xyz="0 0 0.004" />
        <parent link="arm_elbow_F10_0_link" />
        <child link="arm_elbow_F10_1_link" />
    </joint>
    <link name="arm_elbow_F10_1_link">

    <inertial>
            <mass value="0.004" />
            <origin xyz="0 0 0" />
            <inertia ixx="2.13666666667e-07" ixy="0" ixz="0" iyy="6.89666666667e-07" iyz="0" izz="4.86666666667e-07" />
	    <dynamics damping="0.5" friction="0.1"/>
        </inertial>

        <visual>
            <origin rpy="0 0 0" xyz=" 0 0 0 " />
            <geometry>
                <mesh filename="file://$(find cookobot-arm)/robot_description/urdf/meshes/arm/F10.stl" scale="0.001 0.001 0.001" />
            </geometry>
            <material name="White" />
        </visual>
        <collision>
            <origin rpy="0 0 0" xyz="0.0 0.0 0.0" />
            <geometry>
                <box size="0.025 0.038 0.004" />
            </geometry>
        </collision>
    </link>

    <joint name="arm_elbow_F10_2_joint" type="fixed">
        <origin rpy="0 0 0" xyz="0 0 0.004" />
        <parent link="arm_elbow_F10_1_link" />
        <child link="arm_elbow_F10_2_link" />
    </joint>
    <link name="arm_elbow_F10_2_link">

    <inertial>
            <mass value="0.004" />
            <origin xyz="0 0 0" />
            <inertia ixx="2.13666666667e-07" ixy="0" ixz="0" iyy="6.89666666667e-07" iyz="0" izz="4.86666666667e-07" />
	    <dynamics damping="0.5" friction="0.1"/>
        </inertial>

        <visual>
            <origin rpy="0 0 0" xyz=" 0 0 0 " />
            <geometry>
                <mesh filename="file://$(find cookobot-arm)/robot_description/urdf/meshes/arm/F10.stl" scale="0.001 0.001 0.001" />
            </geometry>
            <material name="White" />
        </visual>
        <collision>
            <origin rpy="0 0 0" xyz="0.0 0.0 0.0" />
            <geometry>
                <box size="0.025 0.038 0.004" />
            </geometry>
        </collision>
    </link>

    <joint name="arm_elbow_F3_0_joint" type="fixed">
        <origin rpy="0 3.14159 0" xyz="0 0 0.002" />
        <parent link="arm_elbow_F10_2_link" />
        <child link="arm_elbow_F3_0_link" />
    </joint>
    <link name="arm_elbow_F3_0_link">

    <inertial>
            <mass value="0.005" />
            <origin xyz="0 0 0" />
            <inertia ixx="2.94166666667e-07" ixy="0" ixz="0" iyy="8.62083333333e-07" iyz="0" izz="6.35416666667e-07" />
	    <dynamics damping="0.5" friction="0.1"/>
        </inertial>

        <visual>
            <origin rpy="0 0 0" xyz=" 0 0 0 " />
            <geometry>
                <mesh filename="file://$(find cookobot-arm)/robot_description/urdf/meshes/arm/F3.stl" scale="0.001 0.001 0.001" />
            </geometry>
            <material name="White" />
        </visual>
        <collision>
            <origin rpy="0 0 0" xyz="0.0 0.0 -0.0045" />
            <geometry>
                <box size="0.025 0.038 0.009" />
            </geometry>
        </collision>
    </link>

    <joint name="arm_wrist_flex_servo_joint" type="fixed">
        <origin rpy="0 3.14159 0" xyz="0 0 -0.0415" />
        <parent link="arm_elbow_F3_0_link" />
        <child link="arm_wrist_flex_servo_link" />
    </joint>
    <link name="arm_wrist_flex_servo_link">

   <inertial>
            <mass value="0.055" />
            <origin xyz="0 0 0" />
            <inertia ixx="0.000017012" ixy="0.0" ixz="0.0" iyy="0.000013258" iyz="0.0" izz="0.000009483" />
	    <dynamics damping="0.5" friction="0.1"/>
        </inertial>

        <visual>
            <origin rpy="0 0 0" xyz=" 0 0 0 " />
            <geometry>
                <mesh filename="file://$(find cookobot-arm)/robot_description/urdf/meshes/arm/ax12_box.stl" scale="0.001 0.001 0.001" />
            </geometry>
            <material name="Black" />
        </visual>
        <collision>
            <origin rpy="0 0 0" xyz="0.0 0.0 -0.01241" />
            <geometry>
                <box size="0.025 0.038 0.04762" />
            </geometry>
        </collision>
    </link>

    <joint name="arm_wrist_flex_joint" type="revolute">
        <origin rpy="0 0 0" xyz="0 0 0" />
        <axis xyz="0 1 0" />
        <limit effort="30" lower="-1.745" upper="1.745" velocity="1.571" />
        <parent link="arm_wrist_flex_servo_link" />
        <child link="arm_wrist_flex_link" />
    </joint>
    <link name="arm_wrist_flex_link">

<inertial>
            <mass value="0.01" />
            <origin xyz="0 0 0" />
            <inertia ixx="1.69270833333e-06" ixy="0" ixz="0" iyy="2.48104166667e-06" iyz="0" izz="3.13208333333e-06" />
	    <dynamics damping="0.5" friction="0.1"/>
        </inertial>

        <visual>
            <origin rpy="0 0 0" xyz=" 0 0 0 " />
            <geometry>
                <mesh filename="file://$(find cookobot-arm)/robot_description/urdf/meshes/arm/F2.stl" scale="0.001 0.001 0.001" />
            </geometry>
            <material name="White" />
        </visual>
        <collision>
            <origin rpy="0 0 0" xyz="0.0 0.0 0.00775" />
            <geometry>
                <box size="0.025 0.0485 0.0375" />
            </geometry>
        </collision>
    </link>

    <joint name="arm_wrist_F3_0_joint" type="fixed">
        <origin rpy="0 3.14159 -1.570795" xyz="0 0.016 0.0265" />
        <parent link="arm_wrist_flex_link" />
        <child link="arm_wrist_F3_0_link" />
    </joint>
    <link name="arm_wrist_F3_0_link">

    <inertial>
            <mass value="0.005" />
            <origin xyz="0 0 0" />
            <inertia ixx="2.94166666667e-07" ixy="0" ixz="0" iyy="8.62083333333e-07" iyz="0" izz="6.35416666667e-07" />
	    <dynamics damping="0.5" friction="0.1"/>
        </inertial>

        <visual>
            <origin rpy="0 0 0" xyz=" 0 0 0 " />
            <geometry>
                <mesh filename="file://$(find cookobot-arm)/robot_description/urdf/meshes/arm/F3.stl" scale="0.001 0.001 0.001" />
            </geometry>
            <material name="White" />
        </visual>
        <collision>
            <origin rpy="0 0 0" xyz="0.0 0.0 -0.0045" />
            <geometry>
                <box size="0.025 0.038 0.009" />
            </geometry>
        </collision>
    </link>

    <joint name="gripper_servo_joint" type="fixed">
        <origin rpy="3.14159 1.570795 0" xyz="-0.02275 0 -0.019" />
        <parent link="arm_wrist_F3_0_link" />
        <child link="gripper_servo_link" />
    </joint>
    <link name="gripper_servo_link">

   <inertial>
            <mass value="0.055" />
            <origin xyz="0 0 0" />
            <inertia ixx="0.000017012" ixy="0.0" ixz="0.0" iyy="0.000013258" iyz="0.0" izz="0.000009483" />
	    <dynamics damping="0.5" friction="0.1"/>
        </inertial>

        <visual>
            <origin rpy="0 0 0" xyz=" 0 0 0 " />
            <geometry>
                <mesh filename="file://$(find cookobot-arm)/robot_description/urdf/meshes/arm/ax12_box.stl" scale="0.001 0.001 0.001" />
            </geometry>
            <material name="Black" />
        </visual>
        <collision>
            <origin rpy="0 0 0" xyz="0.0 0.0 -0.01241" />
            <geometry>
                <box size="0.025 0.038 0.04762" />
            </geometry>
        </collision>
    </link>

    <!-- finger 1 -->
    <joint name="gripper_joint" type="revolute">
        <origin rpy="0 0 0" xyz="0 0 0" />
        <axis xyz="0 1 0" />
        <limit effort="30" lower="-0.40" upper="0.46" velocity="0.785" />
        <parent link="gripper_servo_link" />
        <child link="gripper_active_link" />
    </joint>
    <link name="gripper_active_link">

    <inertial>
            <mass value="0.010" />
            <origin xyz="0 0 0" />
            <inertia ixx="0.000001" ixy="0.0" ixz="0.0" iyy="0.000001" iyz="0.0" izz="0.000001" />
        </inertial>

        <visual>
            <origin rpy="0 0 0" xyz=" 0 0 0 " />
            <geometry>
                <mesh filename="file://$(find cookobot-arm)/robot_description/urdf/meshes/arm/F2.stl" scale="0.001 0.001 0.001" />
            </geometry>
            <material name="White" />
        </visual>
        <collision>
            <origin rpy="0 0 0" xyz="0.0 0.0 0.00775" />
            <geometry>
                <box size="0.025 0.0485 0.0375" />
            </geometry>
        </collision>
    </link>
    <joint name="gripper_active_finger_joint" type="fixed">
        <origin rpy="0 0 0" xyz="0 0 0.0265" />
        <parent link="gripper_active_link" />
        <child link="gripper_active_finger_link" />
    </joint>
    <link name="gripper_active_finger_link">

<inertial>
            <mass value="0.015" />
            <origin xyz="0 0 0" />
            <inertia ixx="8.129225e-06" ixy="0" ixz="0" iyy="9.469562625e-06" iyz="0" izz="2.271562625e-06" />
	    <dynamics damping="0.5" friction="0.1"/>
        </inertial>

        <visual>
            <origin rpy="0 0 0" xyz=" 0 0 0 " />
            <geometry>
                <mesh filename="file://$(find cookobot-arm)/robot_description/urdf/meshes/arm/turtlebot_finger.stl" scale="0.001 0.001 0.001" />
            </geometry>
            <material name="Green" />
        </visual>
        <collision>
            <origin rpy="0 0 0" xyz="0.02645 0.0 -0.00655" />
            <geometry>
                <box size="0.0783 0.03801 0.0193" />
            </geometry>
        </collision>
    </link>

    <joint name="gripper_static_joint" type="fixed">
        <origin rpy="0 3.14159 0" xyz="0 0 -0.0415" />
        <parent link="gripper_servo_link" />
        <child link="gripper_static_link" />
    </joint>
    <link name="gripper_static_link">

<inertial>
            <mass value="0.005" />
            <origin xyz="0 0 0" />
            <inertia ixx="2.94166666667e-07" ixy="0" ixz="0" iyy="8.62083333333e-07" iyz="0" izz="6.35416666667e-07" />
	    <dynamics damping="0.5" friction="0.1"/>
        </inertial>

        <visual>
            <origin rpy="0 0 0" xyz=" 0 0 0 " />
            <geometry>
                <mesh filename="file://$(find cookobot-arm)/robot_description/urdf/meshes/arm/F3.stl" scale="0.001 0.001 0.001" />
            </geometry>
            <material name="White" />
        </visual>
        <collision>
            <origin rpy="0 0 0" xyz="0.0 0.0 -0.0045" />
            <geometry>
                <box size="0.025 0.038 0.009" />
            </geometry>
        </collision>
    </link>

    <joint name="gripper_static_finger_joint" type="fixed">
        <origin rpy="0 0 3.14159" xyz="0 0 0" />
        <parent link="gripper_static_link" />
        <child link="gripper_static_finger_link" />
    </joint>
    <link name="gripper_static_finger_link">

<inertial>
            <mass value="0.015" />
            <origin xyz="0 0 0" />
            <inertia ixx="8.129225e-06" ixy="0" ixz="0" iyy="9.469562625e-06" iyz="0" izz="2.271562625e-06" />
	    <dynamics damping="0.5" friction="0.1"/>
        </inertial>

        <visual>
            <origin rpy="0 0 0" xyz=" 0 0 0 " />
            <geometry>
                <mesh filename="file://$(find cookobot-arm)/robot_description/urdf/meshes/arm/turtlebot_finger.stl" scale="0.001 0.001 0.001" />
            </geometry>
            <material name="Green" />
        </visual>
        <collision>
            <origin rpy="0 0 0" xyz="0.02645 0.0 -0.00655" />
            <geometry>
                <box size="0.0783 0.03801 0.0193" />
            </geometry>
        </collision>
    </link>



    <!-- shoulder pan joint--> 
    <dynamixel_AX12_fixed parent="arm_base_link" name="arm_shoulder_pan_servo">
      <origin xyz="0 0 0" rpy="${M_PI/2} 0 ${M_PI/2}"/>
    </dynamixel_AX12_fixed>
    <bioloid_F3_revolute parent="arm_shoulder_pan_servo_link" name="arm_shoulder_pan" color="${color}"
                         vlimit="${joints_vlimit}" llimit="${pan_llimit}" ulimit="${pan_ulimit}">
      <origin xyz="0 ${AX12_WIDTH/2} 0" rpy="${-M_PI/2} ${M_PI/2} ${M_PI}"/>
    </bioloid_F3_revolute> -->

    <!-- shoulder lift joint -->
    <dynamixel_AX12_fixed parent="arm_shoulder_pan_link" name="arm_shoulder_lift_servo">
      <origin xyz="0 0 ${-AX12_HEIGHT-F10_HEIGHT+0.001}" rpy="0 ${M_PI} 0"/>
    </dynamixel_AX12_fixed>
    <bioloid_F4_revolute parent="arm_shoulder_lift_servo_link" name="arm_shoulder_lift" color="${color}"
                         vlimit="${joints_vlimit}" llimit="${shoulder_llimit}" ulimit="${shoulder_ulimit}">
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </bioloid_F4_revolute>
    <bioloid_F10_fixed parent="arm_shoulder_lift_link" name="arm_shoulder_F10_0" color="${color}">
      <origin xyz="0 0 ${F4_HEIGHT+F10_HEIGHT/2}" rpy="0 0 0"/>
    </bioloid_F10_fixed>
    <bioloid_F10_fixed parent="arm_shoulder_F10_0_link" name="arm_shoulder_F10_1" color="${color}">
      <origin xyz="0 0 ${F10_HEIGHT}" rpy="0 0 0"/>
    </bioloid_F10_fixed>
    <bioloid_F10_fixed parent="arm_shoulder_F10_1_link" name="arm_shoulder_F10_2" color="${color}">
      <origin xyz="0 0 ${F10_HEIGHT}" rpy="0 0 0"/>
    </bioloid_F10_fixed>
    <bioloid_F3_fixed parent="arm_shoulder_F10_2_link" name="arm_shoulder_F3_0" color="${color}">
      <origin xyz="0 0 ${F10_HEIGHT/2}" rpy="0 ${M_PI} 0"/>
    </bioloid_F3_fixed> -->

    <!-- elbow joint -->
    <dynamixel_AX12_fixed parent="arm_shoulder_F3_0_link" name="arm_elbow_flex_servo">
      <origin xyz="0 0 ${-AX12_HEIGHT-F10_HEIGHT+0.001}" rpy="0 ${M_PI} 0"/>
    </dynamixel_AX12_fixed>
    <bioloid_F4_revolute parent="arm_elbow_flex_servo_link" name="arm_elbow_flex" color="${color}"
                         vlimit="${joints_vlimit}" llimit="${elbow_llimit}" ulimit="${elbow_ulimit}">
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </bioloid_F4_revolute>
    <bioloid_F10_fixed parent="arm_elbow_flex_link" name="arm_elbow_F10_0" color="${color}">
      <origin xyz="0 0 ${F4_HEIGHT+F10_HEIGHT/2}" rpy="0 0 0"/>
    </bioloid_F10_fixed>
    <bioloid_F10_fixed parent="arm_elbow_F10_0_link" name="arm_elbow_F10_1" color="${color}">
      <origin xyz="0 0 ${F10_HEIGHT}" rpy="0 0 0"/>
    </bioloid_F10_fixed>
    <bioloid_F10_fixed parent="arm_elbow_F10_1_link" name="arm_elbow_F10_2" color="${color}">
      <origin xyz="0 0 ${F10_HEIGHT}" rpy="0 0 0"/>
    </bioloid_F10_fixed>
    <bioloid_F3_fixed parent="arm_elbow_F10_2_link" name="arm_elbow_F3_0" color="${color}">
      <origin xyz="0 0 ${F10_HEIGHT/2}" rpy="0 ${M_PI} 0"/>
    </bioloid_F3_fixed>
   

  <!-- wrist joint -->
    <dynamixel_AX12_fixed parent="arm_elbow_F3_0_link" name="arm_wrist_flex_servo">
      <origin xyz="0 0 ${-AX12_HEIGHT-F10_HEIGHT+0.001}" rpy="0 ${M_PI} 0"/>
    </dynamixel_AX12_fixed>
    <bioloid_F2_revolute parent="arm_wrist_flex_servo_link" name="arm_wrist_flex" color="${color}"
                         vlimit="${joints_vlimit}" llimit="${wrist_llimit}" ulimit="${wrist_ulimit}">
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </bioloid_F2_revolute> 






</robot>
